/**
 * RSS 2.0 / Atom parsing and article-HTML → plain text, for the v0.6 `daily:*` modules.
 *
 * No XML dependency on purpose. These four feeds are machine-generated by two engines (WordPress
 * and Pangea CMS) and a full parser buys nothing here — but a hand-rolled one has to be honest
 * about what it does NOT handle, so:
 *  - namespaced elements are matched by their literal qualified name (`dc:creator`), because that
 *    is what the feeds emit; a feed that bound the namespace to a different prefix would be missed.
 *  - CDATA is unwrapped before entity decoding; doing it the other way round corrupts any body
 *    containing `&amp;` inside CDATA.
 *  - the first matching element wins, which is what every field here wants.
 */
import { decodeHtml, decodeXml } from './text';

export interface Enclosure {
  url: string;
  type: string | null;
  bytes: number | null;
}

export interface FeedItem {
  title: string;
  link: string;
  guid: string | null;
  /** ISO `YYYY-MM-DD`, or null when the feed's date is unparseable. */
  published: string | null;
  /** The raw date string, kept so a parse failure is debuggable rather than invisible. */
  publishedRaw: string | null;
  /** `<description>` / `<summary>`, as it arrived (may be HTML). */
  summaryHtml: string;
  /** `<content:encoded>` / `<content>` — the full body, when the feed carries one. */
  contentHtml: string | null;
  /** `<dc:creator>` / `<author><name>`. The CC BY credit line depends on this. */
  author: string | null;
  categories: string[];
  enclosures: Enclosure[];
}

const unwrap = (s: string): string => {
  const cdata = /^\s*<!\[CDATA\[([\s\S]*?)\]\]>\s*$/.exec(s);
  return decodeXml(cdata ? cdata[1]! : s).trim();
};

/** First `<name>…</name>` inside `block`, CDATA-unwrapped and entity-decoded. */
function tag(block: string, name: string): string | null {
  const m = new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)</${name}>`, 'i').exec(block);
  return m ? unwrap(m[1]!) : null;
}

function tagAll(block: string, name: string): string[] {
  const out: string[] = [];
  const re = new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)</${name}>`, 'gi');
  for (let m = re.exec(block); m; m = re.exec(block)) out.push(unwrap(m[1]!));
  return out;
}

const attr = (openTag: string, name: string): string | null => {
  const m = new RegExp(`\\b${name}\\s*=\\s*["']([^"']*)["']`, 'i').exec(openTag);
  return m ? decodeXml(m[1]!) : null;
};

/**
 * ISO date from an RFC-822 (RSS) or RFC-3339 (Atom) timestamp.
 *
 * Returns null rather than today's date on failure — a wrong date silently files an article under
 * the wrong day forever, and the id is date-scoped, so it would also mint a duplicate.
 */
export function isoDate(raw: string | null): string | null {
  if (!raw) return null;
  const ms = Date.parse(raw);
  if (Number.isNaN(ms)) return null;
  return new Date(ms).toISOString().slice(0, 10);
}

function firstLink(block: string): string {
  // RSS: <link>url</link>. Atom: <link rel="alternate" href="url"/> — and Atom feeds also carry
  // rel="self"/"edit" links, so an unqualified first-href match points at the feed, not the item.
  const rss = tag(block, 'link');
  if (rss && /^https?:/i.test(rss)) return rss;
  const links = block.match(/<link\b[^>]*\/?>/gi) ?? [];
  const alternate = links.find((l) => (attr(l, 'rel') ?? 'alternate') === 'alternate');
  return attr(alternate ?? links[0] ?? '', 'href') ?? '';
}

function enclosuresOf(block: string): Enclosure[] {
  const out: Enclosure[] = [];
  for (const raw of block.match(/<(?:enclosure|media:content)\b[^>]*\/?>/gi) ?? []) {
    const url = attr(raw, 'url');
    if (!url) continue;
    const len = attr(raw, 'length') ?? attr(raw, 'fileSize');
    out.push({ url, type: attr(raw, 'type'), bytes: len && /^\d+$/.test(len) ? Number(len) : null });
  }
  return out;
}

/** Parse an RSS 2.0 or Atom document into items, in feed order. */
export function parseFeed(xml: string): FeedItem[] {
  const blocks = xml.match(/<(item|entry)\b[\s\S]*?<\/\1>/gi) ?? [];
  return blocks.map((block) => {
    const publishedRaw =
      tag(block, 'pubDate') ?? tag(block, 'published') ?? tag(block, 'dc:date') ?? tag(block, 'updated');
    return {
      title: tag(block, 'title') ?? '',
      link: firstLink(block),
      guid: tag(block, 'guid') ?? tag(block, 'id'),
      published: isoDate(publishedRaw),
      publishedRaw,
      summaryHtml: tag(block, 'description') ?? tag(block, 'summary') ?? '',
      contentHtml: tag(block, 'content:encoded') ?? tag(block, 'content'),
      author: tag(block, 'dc:creator') ?? tag(block, 'author') ?? null,
      categories: tagAll(block, 'category'),
      enclosures: enclosuresOf(block),
    };
  });
}

/**
 * Article HTML → readable plain text with blank lines between paragraphs.
 *
 * Everything dropped here is dropped for a reason: `<script>`/`<style>` are not prose; figures and
 * images cannot be bundled anyway (VOA's wire-agency photos are explicitly excluded from the
 * public-domain grant, and Global Voices images are often third-party); `<aside>`/`<nav>` are the
 * "read more" furniture every CMS injects mid-article.
 */
export function htmlToText(html: string): string {
  const stripped = html
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<(script|style|noscript|iframe|form)\b[\s\S]*?<\/\1>/gi, '')
    .replace(/<(figure|figcaption|aside|nav|footer)\b[\s\S]*?<\/\1>/gi, '')
    .replace(/<img\b[^>]*>/gi, '')
    .replace(/<\/(p|div|li|h[1-6]|blockquote|tr)\s*>/gi, '\n\n')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<[^>]+>/g, '');
  return decodeHtml(stripped)
    .split('\n')
    .map((l) => l.replace(/[ \t ]+/g, ' ').trim())
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

/** Characters of real text, ignoring whitespace — the honest way to compare two extractions. */
export const textLength = (s: string): number => s.replace(/\s+/g, '').length;
